#!/bin/bash -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# root
cd $SCRIPT_DIR

# commit
set +e
git add .
git commit -m "$(whoami) enviar"
git push
set -e

# upload
aws s3 sync --delete site s3://onair2.fantasfm.com/
