#!/bin/bash -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# root
cd $SCRIPT_DIR

# clean
rm -rf site/*html

# generate
go run generate.go

# commit
set +e
git add .
git commit -m "$(whoami) enviar"
git push
set -e

# upload
aws s3 sync --delete site s3://963345548549-onair2/

# clean
rm -rf site/*html

# done
echo "Enviado!"
sleep 30
